### ISSUE TITLE
Mobile API

### ISSUE THREAD

**Issue by abangkis** [spreadthesource/wooki#93]
Hi, lets say somewhere far-far away in the future. I want to create a mobile client for wooki. For example for android. Is such API already available, in concept ? what's your take on the issue.

**Comment by robink** [comment]
We are planning to provide a JSON REST API with all the possibilities for reading documents, but maybe some limitations for writing. 

We already tried to implement Jersey as a REST layer, but we faced some difficulties to integrate it correctly with Tapestry. 
But, for sure, it is one of our top priorities!

**Comment by spycos** [comment]
Jboss restEasy works quite nice

**Comment by robink** [comment]
yes, RESTEasy has also a nice T5 integration thanks to the tynamo team.
http://tynamo.org/tapestry-resteasy+guide

Actually we have to choose between Apache CXF and RESTEasy.

**Comment by spycos** [comment]
What is the idea? Build  a native app or use the web as phone app.

There's a new jQuery project ... jquery-mobile which allows you to create a mobile experience to mobile version... maybe is the best aproach ..since tapestry has the localizable templates and you can even add template version for mobile.

This way ... web will be in theory supported in all phones and no need to native application installed on mobile too.

Apache CFX, just used a couple of years ago ... and it was quite nice... but now I'm quite happy with RestEasy from jboss ... you can even add plugion to generate a javascript version (complete API) for your rest services... so developement can be really fast and with only the cost to add new servelt + mapping or listener...

Integration on resteasy on your app server is quite simple... no need to any hack from tapestry side... just ignore the resteasy servlet mapping context from tapestry side...
